version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "generate code from .proto files"
    cmds:
      - protoc --proto_path=protos/proto protos/proto/sso/*.proto --go_out=protos/gen/go --go_opt=paths=source_relative --go-grpc_out=protos/gen/go --go-grpc_opt=paths=source_relative